#!/system/bin/sh
mount -o remount,rw /system
if [ -e /sdcard/customdensity ]
then
source /sdcard/customdensity
if [ $customdensity -gt $(getprop ro.sf.lcd_density) ]
then
compare=$(expr $customdensity - $(getprop ro.sf.lcd_density) )
else
compare=$(expr $(getprop ro.sf.lcd_density) - $customdensity )
fi
echo "Comparison is "$compare
setprop comparedensity $compare
if [ 180 -gt $customdensity ]
then
echo "Aborting; Custom density is less than 180"
exit
fi
if [ $(getprop comparedensity) -gt 180 ]
then
echo "Aborting; Density comparison is more than 180"
exit
fi
if [ $customdensity != $(getprop ro.sf.lcd_density) ];
	then
	    setprop customdensity $customdensity
fi
else
setprop customdensity $(getprop ro.sf.lcd_density)
fi
mount -o remount,ro /system
