#!/system/bin/sh
stockdensity=$(getprop ro.sf.lcd_density);
if [ -e /sdcard/customdensity ]
then
cp /sdcard/customdensity /data/local/tmp/customdensity
else
cp /data/local/tmp/stockdensity /data/local/tmp/customdensity
fi
if [ -e /data/local/tmp/customdensity ]
then
chmod 0775 /data/local/tmp/stockdensity
. /data/local/tmp/stockdensity
chmod 0775 /data/local/tmp/customdensity
. /data/local/tmp/customdensity
setprop stockdensity $stockdensity
if [ ! -z $customdensity ]
then
setprop customdensity $customdensity
else
setprop customdensity $stockdensity
fi
if [ $(getprop customdensity) -gt $(getprop stockdensity) ]
then
compare=$(expr $(getprop customdensity) - $(getprop stockdensity))
else
compare=$(expr $(getprop stockdensity) - $(getprop customdensity))
fi
echo "Comparison is "$compare
setprop comparedensity $compare
if [ 180 -gt $(getprop customdensity) ]
then
echo "Aborting; Custom density is less than 180"
exit
fi
if [ $(getprop comparedensity) -gt 180 ]
then
echo "Aborting; Density comparison is more than 180"
exit
fi
currentdensity=$(getprop ro.sf.lcd_density);
if [ $(getprop customdensity) != "$currentdensity" ];
	then
		setprop ro.sf.lcd_density $customdensity
		mount -o remount,rw /system
		sed -i '/ro.sf.lcd_density=/d' /system/build.prop;
		echo 'ro.sf.lcd_density='$(getprop customdensity) >> /system/build.prop;
		mount -o remount,ro /system
fi
else
echo 'customdensity='$(getprop customdensity) > /sdcard/customdensity
echo 'stockdensity='$stockdensity > /data/local/tmp/stockdensity
setprop stockdensity $stockdensity
fi
