#!/system/bin/sh
mount -o remount,rw /system
if [ -e /sdcard/customdensity ]
then
cp /sdcard/customdensity /data/local/tmp/customdensity
. /data/local/tmp/customdensity
. /system/densitybackup.prop
if [ ! -z $customdensity ]
then
setprop customdensity $customdensity
else
setprop customdensity $stockdensity
fi
if [ $(getprop customdensity) -gt $(getprop stockdensity) ]
then
compare=$(expr $(getprop customdensity) - $(getprop stockdensity))
else
compare=$(expr $(getprop stockdensity) - $(getprop customdensity))
fi
echo "Comparison is "$compare
setprop comparedensity $compare
if [ 180 -gt $(getprop customdensity) ]
then
echo "Aborting; Custom density is less than 180"
exit
fi
if [ $(getprop comparedensity) -gt 180 ]
then
echo "Aborting; Density comparison is more than 180"
exit
fi
if [ $(getprop customdensity) != $(getprop ro.sf.lcd_density) ];
	then
		setprop ro.sf.lcd_density $customdensity
		sed -i '/customdensity=/d' /system/build.prop;
		sed -i '/ro.sf.lcd_density=/d' /system/build.prop;
		echo 'customdensity='$(getprop customdensity) >> /system/build.prop;
		echo 'ro.sf.lcd_density='$(getprop customdensity) >> /system/build.prop;
		
fi
else
if [ -z $(getprop stockdensity) ];
then
if [ ! -e /system/densitybackup.prop ]
then
echo 'stockdensity='$(getprop ro.sf.lcd_density) > /system/densitybackup.prop;
fi
. /system/densitybackup.prop
echo 'stockdensity='$(getprop ro.sf.lcd_density) >> /system/build.prop;
echo 'customdensity='$(getprop ro.sf.lcd_density) >> /system/build.prop;
fi
. /system/densitybackup.prop
sed -i '/ro.sf.lcd_density=/d' /system/build.prop
echo 'ro.sf.lcd_density='$stockdensity >> /system/build.prop
fi
mount -o remount,ro /system
