#!/system/bin/sh
setprop stocktcpcong $(cat /proc/sys/net/ipv4/tcp_congestion_control)
setprop stockscheduler $(cat /sys/block/mmcblk0/queue/scheduler | sed 's/.*[[]//g' | sed 's/[]].*//g')
setprop stockgov $(ls /sys/devices/system/cpu/cpufreq)
setprop stockminkhz $(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq)
setprop stockmaxkhz $(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
cmd='sh /system/etc/init.plain.kerneltweak.sh'
sha=0
if [ -z $(getprop updateinterval) ]
then
updateinterval=5
setprop updateinterval $updateinterval
fi
echo "Plain-tweak watcher is online"
#Using original watch scripting from https://gist.github.com/mikesmullin/6401258
path=/sdcard/plaintweak
update_sha() {
  sha=`sha1sum $path`
}
update_sha
previous_sha=$sha
build() {
  echo "Change detected; Invoking /system/etc/init.plain.kerneltweak.sh"
  $cmd
}
compare() {
  update_sha
  if [[ $sha != $previous_sha ]] ; then
    build
    previous_sha=$sha
  fi
( echo $(getprop maxkhz) > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo $(getprop minkhz) > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo $(getprop gov) > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor

if [ -z $(getprop maxkhz2) ]
then
echo $(getprop maxkhz) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
else
echo $(getprop maxkhz2) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
fi
if [ -z $(getprop minkhz2) ]
then
echo $(getprop minkhz) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
else
echo $(getprop minkhz2) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
fi
if [ -z $(getprop gov2) ]
then
echo $(getprop gov) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
else
echo $(getprop gov2) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
fi

if [ -z $(getprop maxkhz2) ]
then
echo $(getprop maxkhz) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
else
echo $(getprop maxkhz2) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
fi
if [ -z $(getprop minkhz2) ]
then
echo $(getprop minkhz) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
else
echo $(getprop minkhz2) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
fi

if [ -z $(getprop gov2) ]
then
echo $(getprop gov) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
else
echo $(getprop gov2) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
fi )

}
trap build SIGINT
trap exit SIGQUIT
while true; do
  compare
  sleep $(getprop updateinterval)
done
